[project]
name = "ok-duet-night-abyss"
version = "0.1.0"
description = "Add your description here"
dependencies = [
    "ok-script[ocr,qt]>=2.0.6",
    "onnxocr-ppocrv5>=0.0.22",
    "opencv-python>=4.13.0.92",
    "openvino>=2026.1.0",
    "playwright>=1.58.0",
    "pynput==1.8.1",
    "PySide6-Essentials==6.11.2",
    "pyside6-fluent-widgets==1.11.3",
    "pywin32==311"
]

[dependency-groups]
dev = [
    "polib>=1.2.0",
]

[tool.uv]
environments = [
    "sys_platform == 'win32'"
]

exclude-dependencies = [
    { package = { name = "pyside6-fluent-widgets" },
      dependencies = ["pyside6"] },
]